// 路径常量：路由表、菜单、跳转都只引用这里，不写裸字符串。
export const paths = {
  login: "/login",
  activate: "/activate",
  claim: "/claim",
  dashboard: "/",
  updates: "/updates",
  orgUnits: "/org/units",
  people: "/people",
  assignments: "/assignments",
  account: "/account",
  clients: "/devices",
  clientPolicy: "/devices/policy",
  processes: "/assets/processes",
  projects: "/assets/projects",
  legacyImport: "/assets/import",
  fieldFiles: "/assets/files",
  auditEvents: "/audit/events",
  auditStats: "/audit/stats",
  reports: "/reports",
} as const;
